<div class='row'>
	<div class='col-md-4'>
	
	</div>
	
	<div class='col-md-4'>
		
		<div class="portlet light">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-picture font-green-sharp"></i>
					<span class="caption-subject font-green-sharp bold uppercase">Change profile photo</span>
				</div>
				
				
			</div>
			<div class="portlet-body">
			<?php 
			if($this->done)
			{
			?>
				<div class="alert alert-success">
					<strong>Success!</strong> You have a new picture!.
				</div>
			<?php 
			}
			if(!empty($this->error))
			{
			?>
				<div class="alert alert-danger">
					<strong>Warning!</strong> Your picture is in invalid format!.
				</div>
			<?php 
			}
			?>				
				<form method='post' action='' enctype="multipart/form-data">
					<input type='file' name='file' onchange='this.form.submit()'/>
				</form>
				
			</div>
		</div>	
	</div>
	
</div>
