<?php 
$redirectSection = $this->p['type'] == Application_Model_Import::IMP_TYPE_LEAD ? 'lead' : 'prospect';
?>
<form id="frm_promote" role="form" enctype="multipart/form-data" method='post'  action='/promote/post/'>


<input type='hidden' name='type' value='<?php echo $this->p['type'] ?>' />
<input type='hidden' name='promote-type' value='<?php echo $this->p['promote-type'] ?>' />	
<input type='hidden' name='ref_id' value='<?php echo $this->p['ref_id'] ?>' />	
<div class="row form-horizontal">
				<div class="col-md-12">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet light">
						<div class="portlet-title">
							<div class="caption col-sm-6">
								<i class="fa fa-user font-green-sharp"></i>
								<span class="caption-subject font-green-sharp bold uppercase">New client for Secure24</span>
							</div>
							
							
						</div>
						<div class="portlet-body">
							
								<div class="form-group">
									
									<div class="col-md-6">

											<textarea class="form-control" placeholder='Call Notes' name='call_notes'></textarea>
									</div>
									<div class='col-md-6'>
										<div class="radio-list">
												<label>
													<input type="radio" name="install" value='New install' checked> New Install
												</label>
												
												<label>
													<input type="radio" name="install" value='Take Over'> Take Over
												</label>
										</div>		
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-2 control-label" >Sales Rep.</label>
									<div class="col-md-4">
											<input type="text" value="" name="sales_rep" class="form-control">
									</div>
									<div class='col-md-4'>
										
											<input type="text" value="" name="sold_date" class="form-control" placeholder='Sold Date'>
										
									</div>
									
									
									
								</div>
								<div class='row'>
										<div class='col-md-6'>
											<div class="form-group">
												<label class="col-md-6 control-label" >Full name</label>
												<div class='col-md-6'>
												
													<input type="text" value="" name="name" class="form-control" placeholder='Name'>
												
											</div>
										</div>
									</div>
									<div class='col-md-6'>
										<div class="form-group">
												<label class="col-md-1 control-label" >Email</label>
												<div class='col-md-7'>
												
													<input type="text" value="" name="email" class="form-control" placeholder='Email'>
												
											</div>
										</div>
									</div>
								</div>
								
									<div class='row'>
										<div class='col-md-6'>
											<div class="form-group">
												<label class="col-md-6 control-label" >Social security #</label>
												<div class='col-md-6'>
												
													<input type="text" value="" name="social_security_no" class="form-control" placeholder='Social Security #'>
												
											</div>
										</div>
									</div>
									<div class='col-md-6'>
										<div class="form-group">
												<label class="col-md-1 control-label" >Date of Birth</label>
												<div class='col-md-7'>
												
													<input type="text" value="" name="beacon_score" class="form-control" placeholder='Date of Birth'>
												
											</div>
										</div>
									</div>
								</div>
								
								
								<div class='row'>
										<div class='col-md-6'>
											<div class="form-group">
												<label class="col-md-6 control-label" >Beacon Score</label>
												<div class='col-md-6'>
												
													<input type="text" value="" name="beacon_score" class="form-control" placeholder='Beacon Score'>
												
											</div>
										</div>
									</div>
									<div class='col-md-6'>
										<div class="form-group">
												<label class="col-md-1 control-label" >Defender ID</label>
												<div class='col-md-7'>
												
													<input type="text" value="" name="beacon_score" class="form-control" placeholder='Defender ID'>
												
											</div>
										</div>
									</div>
								</div>
								
								
								<div class='row'>
										<div class='col-md-6'>
											<div class="form-group">
												<label class="col-md-6 control-label" >Home Phone</label>
												<div class='col-md-6'>
												
													<input type="text" value="" name="home_phone" class="form-control" placeholder='Home Phone'>
												
												</div>
											</div>
											
											<div class="form-group">
												<label class="col-md-6 control-label" >Cell Phone</label>
												<div class='col-md-6'>
												
													<input type="text" value="" name="cell_phone" class="form-control" placeholder='Cell Phone'>
												
												</div>
											</div>
									</div>
									<div class='col-md-6'>
										<div class="form-group">
												<label class="col-md-1 control-label" >Address</label>
												<div class='col-md-7'>
												
													<textarea name='address' class='form-control'></textarea>
												
											</div>
										</div>
									</div>
								</div>
								
								
								<div class='row'>
										<div class='col-md-6'>
											<div class="form-group">
												<label class="col-md-6 control-label" >Emergency Contact</label>
												<div class='col-md-6'>
												
													<input type="text" value="" name="emergency_contact" class="form-control" placeholder='Emergency Contact'>
												
											</div>
										</div>
									</div>
									<div class='col-md-6'>
										<div class="form-group">
												<label class="col-md-1 control-label" >Contact Number</label>
												<div class='col-md-7'>
												
													<input type="text" value="" name="contact_number" class="form-control" placeholder='Contact Number'>
												
											</div>
										</div>
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-6 control-label" >Monthly Fee</label>
									<div class="col-md-6">
											<div class="radio-list">
											<label>
												<input type="radio" name="monthly" value="36.99" checked> $ 36.99
											</label>
											
											<label>
												<input type="radio" name="monthly" value="42.99" checked> $ 42.99
											</label>
											
											<label>
												<input type="radio" name="monthly" value="44.99" checked> $ 44.99
											</label>
											
											<label>
												<input type="radio" name="monthly" value="pulse" checked> Pulse
											</label>
											
											<label>
												<input type="radio" name="monthly" value="Small Bussines" checked> Small Bussines
											</label>
											
											
											
											
											
										</div>

									</div>
								</div>
								
								
								
								
						
						</div>
					</div>
				</div>	
</div>


<h1>Credit card or Bank Account</h1>

<div class="row form-horizontal">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet light">
				<div class="portlet-title">
					<div class="caption col-sm-6">
						<i class="fa  fa-credit-card font-green-sharp"></i>
						<span class="caption-subject font-green-sharp bold uppercase">Credit Card</span>
					</div>
					
					
				</div>
				<div class="portlet-body">
								<div class="form-group">
									<label class="col-md-4 control-label" >Credit Card #</label>
									<div class="col-md-6">

											<input type="text" value="" name="credit_card_number" class="form-control">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Expiration Date</label>
									<div class="col-md-6">

											<input type="text" value="" name="credit_card_expiration_date" class="form-control">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >CCV</label>
									<div class="col-md-6">

											<input type="text" value="" name="credit_card_ccv" class="form-control">
									</div>
								</div>
								
								
				</div>
			</div>	
		</div>
</div>



<div class="row form-horizontal">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet light">
				<div class="portlet-title">
					<div class="caption col-sm-6">
						<i class="fa   fa-bank font-green-sharp"></i>
						<span class="caption-subject font-green-sharp bold uppercase">Bank Account</span>
					</div>
					
					
				</div>
				<div class="portlet-body">
								<div class="form-group">
									<label class="col-md-4 control-label" >Bank Name</label>
									<div class="col-md-6">

											<input type="text" value="" name="bank_name" class="form-control">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Account #</label>
									<div class="col-md-6">

											<input type="text" value="" name="account_number" class="form-control">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Routing #</label>
									<div class="col-md-6">

											<input type="text" value="" name="routing_number" class="form-control">
									</div>
								</div>
								
								
				</div>
			</div>	
		</div>
</div>


<div class="row form-horizontal">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet light">
				<div class="portlet-title">
					<div class="caption col-sm-6">
						<i class="fa  fa-calendar font-green-sharp"></i>
						<span class="caption-subject font-green-sharp bold uppercase">Instalation details</span>
					</div>
					
					
				</div>
				<div class="portlet-body">
								<div class="form-group">
									<label class="col-md-4 control-label" >Install Date</label>
									<div class="col-md-6">

											<input type="text" value="" name="install_date" class="form-control date">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Install time</label>
									<div class="col-md-6">

											<input type="text" value="" name="install_time" class="form-control">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Scheduled</label>
									<div class="col-md-6">

											<select class="form-control" name="install_scheduled">
												<option>No</option>
												<option>Yes</option>
											</select>
									</div>
								</div>
								
								
				</div>
			</div>	
		</div>
</div>

<div class="row form-horizontal">
	<div class="col-md-12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
			<div class="portlet light">
				<div class="portlet-title">
					<div class="caption col-sm-6">
						<i class="fa   fa-umbrella font-green-sharp"></i>
						<span class="caption-subject font-green-sharp bold uppercase">Insurance</span>
					</div>
					
					
				</div>
				<div class="portlet-body">
								<div class="form-group">
									<label class="col-md-4 control-label" >Insurance Agent's Name:</label>
									<div class="col-md-6">

											<input type="text" value="" name="insurance_agent_name" class="form-control date">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Agency</label>
									<div class="col-md-6">

											<input type="text" value="" name="ins_agency" class="form-control">
									</div>
								</div>
								
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Phone Number</label>
									<div class="col-md-6">

											<input type="text" value="" name="<?php Ez_Interface_Form::sanitizeInput('Ins Phone Number') ?>" class="form-control">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Email</label>
									<div class="col-md-6">

											<input type="text" value="" name="<?php Ez_Interface_Form::sanitizeInput('Ins Email') ?>" class="form-control">
									</div>
								</div>
								
								<div class="form-group">
									<label class="col-md-4 control-label" >Address</label>
									<div class="col-md-6">

											<textarea name="<?php Ez_Interface_Form::sanitizeInput('Ins Address') ?>" class="form-control"></textarea>
									</div>
								</div>
								
								<div class="form-group">
									<div class="col-md-offset-4 col-md-8">
									
															<?php 
															if(isset($this->p['imp_id']) && $this->p['imp_id'] > 0)
															{
																?>
																<input type='hidden' name='next_url' value='/<?php echo $redirectSection?>/process/id/<?php echo $this->p['imp_id']?>' />
																	<a href="javascript:;" class="btn green" onclick='saveThisEntry()'>
															<i class="fa fa-save"></i> Save / Next </a>
																<?php
															}
															else 
															{
																?>
																<input type='hidden' name='next_url' value='/<?php echo $redirectSection?>/' />
																<a href="javascript:;" class="btn green" onclick='saveThisEntry()'>
															<i class="fa fa-save"></i> Save </a>
																<?php
															}
															?>
									
									</div>
								</div>	
								
								
				</div>
			</div>	
		</div>
</div>
<script>
function saveThisEntry()
{
	$('#frm_promote').submit();
	
}
</script>
</form>	