<?php 
if(isset($this->data) && count($this->data))
{
	$cnt = 0;
	foreach ($this->data as $data)
	{
		?>
		<div class="form-group">
									<label  class="col-md-2 control-label"><?php echo $data?></label>
									<div class="col-md-4">
									
											<select class='form-control' name='data[<?php echo $cnt?>]'>
												<?php 
												$selected = isset($this->sel[$cnt]) ? $this->sel[$cnt] : 0;
												echo App_Form_Select::simpleBuild($this->fields, $selected);
												?>
											</select>
										</div>
								</div>
		
		<?php
		$cnt++;
	}
	?>
	
	<div class="form-group" id='blockui_portlet_body'>
									<div class="col-md-offset-2 col-md-10">
										<a href="javascript:;" class="btn green" onclick='saveImport()'>
															<i class="fa fa-plus"></i> Save Import / Edit </a>
									</div>
	</div>
	
	<?php
}
?>
<input type='hidden' id='imp_id' value='<?php echo $this->imp_id?>' />