<div class="row ">
				<div class="col-md-12">
					<!-- BEGIN SAMPLE FORM PORTLET-->
					<div class="portlet light">
						<div class="portlet-title">
							<div class="caption col-sm-6">
								<i class="fa fa-list font-green-sharp"></i>
								<span class="caption-subject font-green-sharp bold uppercase">List imports</span>
							</div>
							<div class="col-sm-6 text-right">
								<a href='/prospect/add-import' class="btn blue"><i class='fa fa-plus-circle'></i> Add new import</a>
							</div>
							
						</div>
						<div class="portlet-body">
							<div class="table-scrollable">
								<table class="table table-hover table-bordered">
								<thead>
								<tr>
									<th>
										 #
									</th>
									<th>
										 Date
									</th>
									<th>
										 File
									</th>
									<th>
										 Status
									</th>
									<th>
										 Actions
									</th>
								</tr>
								</thead>
								<tbody>
								<?php 
								$cnt = 0;
								if(isset($this->imports) && count($this->imports))
								{
									foreach ($this->imports as $imp)
									{
										if($imp['cnt_to_do'] == 0 && $imp['cnt_do'] == 0)
										{
											continue;
										}
										$cnt++;
									?>
								<tr>
									<td><?php echo $cnt;?></td>
									<td><?php echo date('m/d/Y H:i', strtotime($imp['imp_date_in']))?></td>
									<td><?php echo $imp['imp_name'];?></td>
									<td>
									<?php 
									if($imp['cnt_to_do'] > 0)
									{
									?>
									<span class="label label-sm label-danger"><?php echo $imp['cnt_to_do'];?> left</span>
									<?php 
									}
									
									if($imp['cnt_do'] > 0)
									{
									?>
									
									<span class="label label-sm label-success"><a style='color:#ffffff;font-weight:bold' href='/lead/index/id/<?php echo $imp['imp_id']?>'><?php echo $imp['cnt_do'];?> processed</a></span>
									<?php 
									}
									?>
									</td>
									<td>
									<?php 
									if($imp['cnt_to_do'] > 0)
									{
									?>
									<a href="/lead/process/id/<?php echo $imp['imp_id']?>" class="btn default btn-xs">
															<i class="fa fa-file-o"></i> Resume </a>
									<?php 
									}
							
									if($imp['cnt_do'] > 0)
									{
									?>
									<a href="/prospect/download/id/<?php echo $imp['imp_id']?>" class="btn blue btn-xs">
															<i class="fa fa-file-o"></i> Download </a>
									<?php 
									}
									?>
									 </td>
								</tr>	
									<?php
									}
								}
								?>
								</tbody>
								</table>
							</div>

						</div>	
					</div>
				</div>
			</div>	
		
					