<div class='row'>
	<div class='col-md-2'></div>
	<div class='col-md-8'>
		<div class="portlet light">
				<div class="portlet-title">
					<div class="caption col-sm-6">
						<i class="fa fa-plus font-green-sharp"></i>
						<span class="caption-subject font-green-sharp bold uppercase">Add new template</span>
					</div>
					<div class="col-sm-6 text-right">
						<a href='/email-template/' class="btn blue"><i class='fa  fa-arrow-left'></i> Discard / Back to email templates</a>
					</div>
					
					
				</div>
				<div class="portlet-body">
					<form  role="form" id='frm_email_template' class='form-horizontal'>
							<div class="form-group">
										<label class="col-md-4 control-label">Platform</label>
										<div class="col-md-6">
												<select name='emt_module' class='form-control'>
													<?php 
													echo App_Form_Select::simpleBuild(Application_Model_Module::getModulesArray(), 0);
													?>
												</select>
											
										</div>
									
									</div>	
							<div class="form-group">
								<label  class="col-md-4 control-label">Name</label>
								<div class="col-md-6">
										<input type="text" class="form-control" name='emt_name' value="">
								</div>
							</div>
							
							<div class="form-group">
								<label  class="col-md-4 control-label">Subject</label>
								<div class="col-md-6">
										<input type="text" class="form-control" name='emt_subject' value="">
								</div>
							</div>
							
							<div class="form-group">
								<label  class="col-md-4 control-label">Message</label>
								<div class="col-md-6">
										<textarea class="form-control" name='emt_message' rows=10></textarea>
								</div>
							</div>
							
							<div class="form-group">
									<div class="col-md-offset-4 col-md-8">
									
										<a href="javascript:;" class="btn green" onclick='saveData()'>
															<i class="fa fa-plus"></i> Add template  </a>
									</div>
								</div>
							
							
					</form>				
				</div>
		</div>				
	</div>
	<div class='col-md-2'></div>
</div>
<script>
function saveData()
{
	$.ajax({
				url : '/email-template/post',
				data : $('#frm_email_template').serialize(),
				type  : 'post',
				success : function(r)
				{
					if(r == 'done')
					{
						bootbox.alert('The new email template has been added!',function(){document.location.href = '/email-template/'});
					}
					else 
					{
						bootbox.alert(r);
					}
				}
		})
}
</script>