<?php 
$session = Bootstrap::getSession();
$admin = $session->admin;
?>
<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.1
Version: 3.2.0
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>EZConect</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css">
<link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css">
<link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="/assets/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet"/>

<!-- END PAGE LEVEL STYLES -->

<!-- BEGIN THEME STYLES -->
<link href="/assets/global/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css">
<link href="/assets/global/css/plugins.css" rel="stylesheet" type="text/css">
<link href="/assets/admin/layout3/css/layout.css" rel="stylesheet" type="text/css">
<link href="/assets/admin/layout3/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color">
<link href="/assets/admin/layout3/css/custom.css" rel="stylesheet" type="text/css">
<!-- END THEME STYLES -->

<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->

<script src="/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="/assets/admin/layout3/scripts/layout.js" type="text/javascript"></script>
<script src="/assets/admin/pages/scripts/inbox.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-datepicker/css/datepicker.css"/>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css"/>
<script type="text/javascript" src="/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/assets/global/plugins/select2/select2.min.js"></script>
<link href="/assets/admin/pages/css/inbox.css" rel="stylesheet" type="text/css"/>

<script>
jQuery(document).ready(function() {       
   // initiate layout and plugins
   Metronic.init(); // init metronic core components
Layout.init(); // init current layout

});
</script>
<link rel="shortcut icon" href="/favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<!-- DOC: Apply "page-header-menu-fixed" class to set the mega menu fixed  -->
<!-- DOC: Apply "page-header-top-fixed" class to set the top menu fixed  -->
<body>
<!-- BEGIN HEADER -->
<div class="page-header">
	<!-- BEGIN HEADER TOP -->
	<div class="page-header-top">
		<div class="container-fluid">
			<!-- BEGIN LOGO -->
			<div class="page-logo">
				<a href="/"><img src="/assets/admin/layout3/img/logo-default.png" alt="logo" class="logo-default"></a>
			</div>
			<!-- END LOGO -->
			<!-- BEGIN RESPONSIVE MENU TOGGLER -->
			<a href="javascript:;" class="menu-toggler"></a>
			<!-- END RESPONSIVE MENU TOGGLER -->
			<!-- BEGIN TOP NAVIGATION MENU -->
			<div class="top-menu">
				<ul class="nav navbar-nav pull-right">
					
					<!-- BEGIN TODO DROPDOWN -->
					<li class="dropdown dropdown-extended dropdown-dark dropdown-tasks" id="header_task_bar">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<i class="icon-calendar"></i>
						<?php 
						$dateParams = array(
								'month' => date('m'),
								'day' => date('d'),
								'year' => date("Y"),
									
						);
						$modelNotificationList = new Application_Model_Notification_List(array(
						'ntf_adm_id' => Sid_Auth_Admin::getAdminId(),
						'date_params'	=> $dateParams,
						'ntf_status' => array(
								Application_Model_Notification::STS_TYPE_NEW,
								Application_Model_Notification::STS_TYPE_NOTIFIED,
				
						
								)
						));

						$ntfs = $modelNotificationList->find();
		
						?>
						<span class="badge badge-default"><?php echo count($ntfs['rows'])?></span>
						</a>
						<ul class="dropdown-menu extended tasks">
							<li class="external">
								<h3>You have <strong><?php echo count($ntfs['rows'])?> pending</strong> tasks for today</h3>
								<a href="/reminder">view all</a>
							</li>
							<li>
								<ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
									<?php 
									if(count($ntfs['rows']))
									{
										foreach ($ntfs['rows'] as $ntf)
										{
											?>
											<li>
										<a href="javascript:;">
										<span class="task">
											<span class="desc"><?php echo $ntf['ntf_note']?> </span>
										</span>
										</a>
									</li>
											<?php
										}
									}
									?>
								</ul>
							</li>
						</ul>
					</li>
					<!-- END TODO DROPDOWN -->
					<li class="droddown dropdown-separator">
						<span class="separator"></span>
					</li>
					<!-- BEGIN INBOX DROPDOWN -->
					<li class="dropdown dropdown-extended dropdown-dark dropdown-inbox" id="header_inbox_bar">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<span class="circle">3</span>
						<span class="corner"></span>
						</a>
						<ul class="dropdown-menu">
							<li class="external">
								<h3>You have <strong>7 New</strong> Messages</h3>
								<a href="javascript:;">view all</a>
							</li>
							<li>
								<ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
									<li>
										<a href="inbox.html?a=view">
										<span class="photo">
										<img src="/assets/admin/layout3/img/avatar2.jpg" class="img-circle" alt="">
										</span>
										<span class="subject">
										<span class="from">
										Lisa Wong </span>
										<span class="time">Just Now </span>
										</span>
										<span class="message">
										Vivamus sed auctor nibh congue nibh. auctor nibh auctor nibh... </span>
										</a>
									</li>
									
									
								</ul>
							</li>
						</ul>
					</li>
					<!-- END INBOX DROPDOWN -->
					<!-- BEGIN USER LOGIN DROPDOWN -->
					<li class="dropdown dropdown-user dropdown-dark">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<img alt="" class="img-circle" src="/get-file/image/?file=/profile/<?php echo Sid_Auth_Admin::getAdminId()?>.jpg">
						<span class="username username-hide-mobile"><?php echo $admin['adm_fullname']?></span>
						</a>
						<ul class="dropdown-menu dropdown-menu-default">
							<li>
								<a href="/profile/edit">
								<i class="icon-pencil"></i> Edit profile </a>
							</li>
							<li>
								<a href="/profile/change-picture">
								<i class="icon-picture"></i> Change Picture </a>
							</li>
							<li>
								<a href="/profile/change-password">
								<i class="icon-lock"></i> Change Password </a>
							</li>
							<li>
								<a href="/logout">
								<i class="icon-key"></i> Log Out </a>
							</li>
							<li>
								<a href="/signature">
								<i class="icon-envelope"></i> Email Signature </a>
							</li>
							<li>
								<a href="/about">
								<i class="icon-info"></i> About </a>
							</li>
						</ul>
					</li>
					<!-- END USER LOGIN DROPDOWN -->
				</ul>
			</div>
			<!-- END TOP NAVIGATION MENU -->
		</div>
	</div>
	<!-- END HEADER TOP -->
	<!-- BEGIN HEADER MENU -->
	<div class="page-header-menu">
		<div class="container-fluid">
			<form class="search-form" action="extra_search.html" method="GET">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Search" name="query">
					<span class="input-group-btn">
					<a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
					</span>
				</div>
			</form>
			
			<!-- BEGIN MEGA MENU -->
			<!-- DOC: Apply "hor-menu-light" class after the "hor-menu" class below to have a horizontal menu with white background -->
			<!-- DOC: Remove data-hover="dropdown" and data-close-others="true" attributes below to disable the dropdown opening on mouse hover -->
			<div class="hor-menu ">
				<ul class="nav navbar-nav">
					<li>
						<a href="/">Dashboard</a>
					</li>
					<?php 
					if($admin['adm_lvl'] == 1)
					{
					?>
					<li>
						<a href="/user" data-hover="megamenu-dropdown" data-close-others="true" data-toggle="dropdown" class="dropdown-toggle">Users <i class="fa fa-angle-down"></i></a>
						<ul class='dropdown-menu'>
							<li>
								<a href='/user'><i class='fa fa-th-list'></i> List</a>
							</li>
							
							<li>
								<a href='/user/add'><i class='fa fa-plus-circle'></i> Add new user</a>
							</li>
							
						</ul>
						
						
					</li>
					<?php 
					}
					?>
					<?php 
					if($admin['adm_lvl'] != 8)
					{
					?>
					<li>
						<a href="/prospect" data-hover="megamenu-dropdown" data-close-others="true" data-toggle="dropdown" class="dropdown-toggle">Prospects <i class="fa fa-angle-down"></i></a>
						<ul class='dropdown-menu'>
							<li>
								<a href='/prospect'><i class='fa fa-th-list'></i >List</a>
							</li>
							
							<li>
								<a href='/prospect/list-import/'><i class='fa fa-th-list'></i> List imports</a>
							</li>
							
							<li>
								<a href='/prospect/add-import'><i class='fa fa-plus-circle'></i> Add new import</a>
							</li>
							
						</ul>
						
						
					</li>
					<?php 
					}
					?>
					<?php 
					if($admin['adm_id'] != 12 &&  $admin['adm_id'] != 13 && $admin['adm_lvl'] != 8)
					{
					?>

					<li>
						<a href="/lead" data-hover="megamenu-dropdown" data-close-others="true" data-toggle="dropdown" class="dropdown-toggle">Leads <i class="fa fa-angle-down"></i></a>
						<ul class='dropdown-menu'>
							<li>
								<a href='/lead'><i class='fa fa-th-list'></i >List</a>
							</li>
							
							<li>
								<a href='/lead/list-import/'><i class='fa fa-th-list'></i> List imports</a>
							</li>
							
							<li>
								<a href='/lead/add-import'><i class='fa fa-plus-circle'></i> Add new import</a>
							</li>
							
						</ul>
						
						
					</li>

					<?php 
					}
					if($admin['adm_lvl'] != 8)
					{
					?>
					<li>
						<a href="/partner" >Partners</a>

					</li>
					<?php
					}
					if($admin['adm_lvl'] == 1)
					{
					?>
					<li>
						<a href="/location" >Location</a>
						
						
						
					</li>
					<li>
						<a href="javascript:;" data-hover="megamenu-dropdown" data-close-others="true" data-toggle="dropdown" class="dropdown-toggle" >Interface <i class="fa fa-angle-down"></i></a>
						<ul class='dropdown-menu'>
							<li><a href='/script'>Scripts</a></li>
							<li><a href='/email-template'>Email templates</a></li>
							<li><a href='/library'>Library</a></li>
						</ul>
						
						
					</li>
					<?php 
					}
					?>
					
					<li>
						<a href="/lost" >Lost </a>
						
						
						
					</li>
					
					
				</ul>
			</div>
			<!-- END MEGA MENU -->
		</div>
	</div>
	<!-- END HEADER MENU -->
</div>
<!-- END HEADER -->
<!-- BEGIN PAGE CONTAINER -->
<div class="page-container">
	<!-- BEGIN PAGE HEAD -->
	<div class="page-head">
		<div class="container-fluid">
			<!-- BEGIN PAGE TITLE -->
			<div class="page-title">
				<?php 
				if(isset($this->pageTitle) && !empty($this->pageTitle))
				{
				?>
				<h1><?php echo $this->pageTitle?> 
				<?php 
				if(isset($this->pageSubtitle) && !empty($this->pageSubtitle))
				{
				?>
				<small><?php echo $this->pageSubtitle?></small>
				<?php 
				}
				?>
				</h1>
				<?php 
				}
				?>
			</div>
			<!-- END PAGE TITLE -->
			<!-- BEGIN PAGE TOOLBAR -->
			<div class="page-toolbar">
				<!-- BEGIN THEME PANEL -->
				<div class="btn-group btn-theme-panel">
                    <a href="#compose-mail" class="btn" data-toggle="modal" title='Compose email'>
                    	<i class="fa fa-envelope-o"></i>
                    </a>
                    
                    <a href="javascript:;" onclick='openLibrary()' class="btn dropdown-toggle"  title='Library'>
                    	<i class="fa  fa-folder-open-o"></i>
                    </a>
                    

                </div>
                        
                <div class="modal fade bs-modal-lg" id="library-modal" tabindex="-1" role="dialog" aria-hidden="true">
					<div class="modal-dialog modal-lg">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
								<h4 class="modal-title">Library</h4>
							</div>
							<div class="modal-body" id='library-main-content'>
							</div>
						</div>
					</div>
				</div>			
<script>
function openLibrary()
{
	$.ajax({
		url : '/library/init-load/',
		success : function(r)
		{
			$('#library-main-content').html(r);
			$('#library-modal').modal('show');  
		}
		});
	
}

function intLbrOpenFolder(fldId)
{
	//int-lbr-list-content
	$.ajax({
				url : '/library/load-list-content/id/' + fldId,
				success : function(r)
				{
					$('#int-lbr-list-content').html(r);
				}
		})
}
</script>                
                <div class="modal fade bs-modal-lg" id="compose-mail" tabindex="-1" role="dialog" aria-hidden="true">
					<div class="modal-dialog modal-lg">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
								<h4 class="modal-title">Compose Email</h4>
							</div>
							<div class="modal-body">
								
									<form class="inbox-compose form-horizontal" id="fileupload" action="javascript:;" method="POST" enctype="multipart/form-data">
	
									<div class="inbox-form-group mail-to">
										<label class="control-label">To:</label>
										<div class="controls controls-to">
											<input type="text" class="form-control" name="to" id='int_mail_to'>
											
										</div>
									</div>
									
									
									<div class="inbox-form-group">
										<label class="control-label">Subject:</label>
										<div class="controls">
											<input type="text" class="form-control" name="subject" id='int_emt_subject'>
										</div>
									</div>
								<?php 
								$modelEmlList = new Application_Model_Email_Template_List(array('module' => Application_Model_Module::MODULE_TYPE_OSC));
								$eml = $modelEmlList->find();
								
								
								$modelSgnList = new Application_Model_Signature_List(array('adm_id' => Sid_Auth_Admin::getAdminId()));
								$sgn  = $modelSgnList->find();
								
								
								?>	
								
									<div class="inbox-form-group">
										<label class="control-label">Platform:</label>
										<div class="controls">
											<div class="radio-list">
												<label>
													<input type="radio" name="int_eml_module" value="<?php echo Application_Model_Module::MODULE_TYPE_OSC?>" checked onclick='intLoadEmailTemplates(<?php echo Application_Model_Module::MODULE_TYPE_OSC?>)'> <span class="label label-sm label-danger">OSC</span>
												</label>
												
												<label>
													<input type="radio" name="int_eml_module" value="<?php echo Application_Model_Module::MODULE_TYPE_SECURE24?>" onclick='intLoadEmailTemplates(<?php echo Application_Model_Module::MODULE_TYPE_SECURE24?>)'> <span class="label label-sm label-primary">Secure24</span>
												</label>
												
											</div>
										</div>
									</div>
									<script>
									function intLoadEmailTemplates(mdl)
									{
										$.ajax({
													url : '/email-template/get-html-options/id/'+mdl,
													success : function(r)
													{
														$('#snd_eml_temaplate').html(r);
													}
											})
									}
									$(function(){
										
												if($('#int_default_email').val() != undefined)
													$('#int_mail_to').val(($('#int_default_email').val()));
										})
									</script>
									<div class="inbox-form-group">
										<label class="control-label">Template:</label>
										<div class="controls">
											<select class="form-control" name="snd_eml_temaplate" id='snd_eml_temaplate' onchange='intPopulateEmail(this.value)'>
												<option value=0>- Select OSC template -</option>
												<?php 
												echo App_Form_Select::build($eml['rows'], array('key' => 'emt_id', 'value' => 'emt_name' ))
												?>
											</select>
										</div>
									</div>
									<div class="inbox-form-group">
										<textarea class="inbox-editor inbox-wysihtml5 form-control" name="message" rows="12" id='int_emt_message'></textarea>
									</div>
									<div class="inbox-form-group">
										<label class="control-label">Signature:</label>
										<div class="controls">
											<select class="form-control" name="snd_sgn_id" id='snd_sgn_id'>
												<option value=0>- Select Signature -</option>
												<?php 
												echo App_Form_Select::build($sgn['rows'], array('key' => 'sgn_id', 'value' => 'sgn_name' ))
												?>
											</select>
										</div>
									</div>
								</form>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn default" data-dismiss="modal">Close</button>
								<button type="button" class="btn blue" onclick='intSendMail()'>Send</button>
							</div>
						</div>
						<!-- /.modal-content -->
					</div>
					<!-- /.modal-dialog -->
			</div>
	<!-- END THEME PANEL -->
			</div>
			<!-- END PAGE TOOLBAR -->
		</div>
	</div>
<script>
function intSendMail()
{
	$.ajax({
				url : '/email-template/send',
				data : {sgn : $('#snd_sgn_id').val(), subject : $('#int_emt_subject').val(), message : $('#int_emt_message').val(), to :   $('#int_mail_to').val()},
				type : 'post',
				success : function(r)
				{
					if(r == 'done')
					{
						bootbox.alert('Mail sent!', function(){
									$('#compose-mail').modal('hide');
							});
					}
					else 
					{
						bootbox.alert(r);
					}
					
				}
		})
}
function intPopulateEmail(v)
{
	$.ajax({
				type : 'post',
				data : {id : v},
				url : '/email-template/load-data',
				dataType : 'json',
				success : function(r)
				{
					if(r.emt_id)
					{
						$('#int_emt_subject').val(r.emt_subject);
						$('#int_emt_message').val(r.emt_message);
					}
					else 
					{
						$('#int_emt_subject').val('');
						$('#int_emt_message').val('');
					}
				}
		});
}
</script>	
	<!-- END PAGE HEAD -->
	<!-- BEGIN PAGE CONTENT -->
	<div class="page-content">
		<div class="container-fluid">

			<!-- BEGIN PAGE BREADCRUMB -->
			<?php 
			if(isset($this->bdcp) && is_array($this->bdcp) && count($this->bdcp))
			{
			?>
			<ul class="page-breadcrumb breadcrumb">
			<?php 
			foreach ($this->bdcp as $bdcp)
			{
				if(isset($bdcp['url']))
				{
					?>
					<li>
					<a href="<?php echo $bdcp['url']?>"><?php echo $bdcp['name']?></a><i class="fa fa-angle-right"></i>
				</li>
					<?php
				}
				else 
				{
					?>
					<li class="active">
					 <?php echo $bdcp['name']?>
				</li>
					<?php
				}
			?>
				
				
				
			<?php 
			}
			?>	
			</ul>
			<?php 
			}
			?>
			<!-- END PAGE BREADCRUMB -->
<?php 
if(isset($this->sectionMenu))
{
	?>
			<style>
				.inbox .inbox-nav li {background:#ffffff !important}	
			</style>
		<div class='row'>
			<div class='col-md-2'>
			<div class="portlet light">
						<div class="portlet-title">
							<div class="caption col-sm-12">
								<i class="fa fa-stumbleupon-circle font-blue-sharp"></i>
								<span class="caption-subject font-blue-sharp bold uppercase"><?php if(!isset($this->sectionTitle) || empty($this->sectionTitle)){?>Section Menu<?php } else {echo $this->sectionTitle;}?></span>
							</div>
							
							
						</div>
						<div class="portlet-body">
						<style>
							.main-menu{
								 border: 0 none;
								    display: block;
								    margin: 0;
								    padding: 0;
								list-style: outside none none;
							}
							.main-menu a{
								color: #485a6a;
								 border: 0 none;
							    display: block;
							    margin: 1px 0 0;
							    padding: 12px 15px;
							    position: relative;
							    text-decoration: none;
								 font-size: 16px;
    							font-weight: 400;
							}
							.main-menu a:hover{
								background: #eff4ff
							}
							
							.sub-menu{
								border: 0 none;
								    display: block;
								    margin: 0;
								    padding: 0;
								margin-left:10px;
								list-style: outside none none;
							}
							.sub-menu a{
								 font-size: 13px;
							}
							.main-menu a.active {
								background: #eff4ff;
							}
						</style>
						<ul class='main-menu'>
								<?php  
								foreach ($this->sectionMenu as $k=>$v)
								{
									?>
									<li >
									
										<a <?php if($k== $this->sectionId){?>class="  active"<?php }?> style='font-size:18px;' href="<?php echo $v['url']?>">
									<?php echo $v['name']?> 
										</a>
									<?php 
									if(isset($v['items']))
									{
										?>
										<ul class='sub-menu'>
										<?php
										foreach ($v['items'] as $sk => $sv)
										{
											?>
												<li >
														<a  <?php if($sk== $this->sectionId){?>class="  active"<?php }?>  href="<?php echo $sv['url']?>">
															<?php echo $sv['name']?> 
													</a>
										</li>
											<?php
										}
										?>
										</ul>
										<?php
									}
									?>	
								</li>
									<?php
								}
								?>
								
								
								
								
							</ul>
						
						</div>
			</div>	
							
			</div>
			
			<div class='col-md-10'>
				<!-- Content Start -->
				<?php	echo $this->layout()->content; ?>
			</div>
			
		</div>
		
	<?php
}
else 
{
	echo $this->layout()->content;
}

?>
		</div>
	</div>
	<!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER -->
<!-- BEGIN PRE-FOOTER -->

<!-- END PRE-FOOTER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="container">
		 <?php echo date("Y")?> &copy; Metronic. All Rights Reserved. - Current system time is: <?php echo date('m/d/Y H:i')?>
	</div>
</div>
<div class="scroll-to-top">
	<i class="icon-arrow-up"></i>
</div>
<!-- END FOOTER -->

<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>